services:
  agravis_mock_interface:
    image: agravis_mock_interface
    command: python run_services/run.py
    privileged: true
    network_mode: "host"
    user: root
    build: .
    environment:
      - SEREACT_PORT=8080
